import React, { useState, useEffect, useContext } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet, ScrollView,
  ActivityIndicator, Alert, Platform, StatusBar,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Share } from 'react-native';
import { useTheme } from '../context/ThemeContext';
import { LanguageContext } from '../context/LanguageContext';
import api from '../config/api';

const MONTH_NAMES = [
  'January','February','March','April','May','June',
  'July','August','September','October','November','December',
];

export default function RevenueDashboardScreen({ navigation }) {
  const now = new Date();
  const [year, setYear]         = useState(now.getFullYear());
  const [month, setMonth]       = useState(now.getMonth() + 1);
  const [selectedZone, setSelectedZone] = useState(null); // null = all
  const [data, setData]         = useState(null);
  const [loading, setLoading]   = useState(true);
  const [exporting, setExporting] = useState(false);
  const { theme, isDark } = useTheme();
  const { t } = useContext(LanguageContext);

  useEffect(() => {
    loadRevenue();
  }, [year, month, selectedZone]);

  const loadRevenue = async () => {
    setLoading(true);
    try {
      const params = { year, month };
      if (selectedZone) params.zone = selectedZone;
      const res = await api.get('/revenue', { params });
      setData(res.data);
    } catch (error) {
      console.error('Revenue load error:', error);
      Alert.alert(t('error'), error.response?.data?.message || t('failedToLoadRevenue'));
    } finally {
      setLoading(false);
    }
  };

  const prevMonth = () => {
    if (month === 1) { setMonth(12); setYear(y => y - 1); }
    else setMonth(m => m - 1);
    setSelectedZone(null);
  };

  const nextMonth = () => {
    if (year === now.getFullYear() && month === now.getMonth() + 1) return;
    if (month === 12) { setMonth(1); setYear(y => y + 1); }
    else setMonth(m => m + 1);
    setSelectedZone(null);
  };

  const isCurrentMonth = year === now.getFullYear() && month === now.getMonth() + 1;
  const formatMoney = (n) => Number(n || 0).toFixed(2);
  const monthLabel = `${MONTH_NAMES[month - 1]} ${year}`;

  // --- Export PDF ---
  const exportPDF = async () => {
    if (!data) return;
    setExporting(true);
    try {
      const rows = (data.byZone || []).map(z =>
        `<tr><td>${z.zone}</td><td style="text-align:center">${z.sessions}</td><td style="text-align:right">${formatMoney(z.revenue)}</td></tr>`
      ).join('');

      const html = `
        <html><head><meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; padding: 32px; color: #111; }
          h1 { font-size: 26px; margin-bottom: 4px; }
          .subtitle { color: #666; font-size: 14px; margin-bottom: 28px; }
          .total-card { background: #fef3c7; border-radius: 12px; padding: 20px 28px; margin-bottom: 28px; }
          .total-label { font-size: 13px; color: #92400e; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; }
          .total-value { font-size: 40px; font-weight: 800; color: #78350f; margin: 4px 0; }
          .meta { font-size: 13px; color: #92400e; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #f3f4f6; padding: 10px 14px; text-align: left; font-size: 13px; color: #374151; }
          td { padding: 12px 14px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
          tr:last-child td { border-bottom: none; }
          .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; text-align: center; }
        </style></head>
        <body>
          <h1>Revenue Report</h1>
          <div class="subtitle">Generated by Laseria · ${new Date().toLocaleDateString()}</div>
          <div class="total-card">
            <div class="total-label">Total Revenue · ${monthLabel}</div>
            <div class="total-value">${formatMoney(data.totalRevenue)}</div>
            <div class="meta">${data.appointmentCount} appointments · ${data.totalSessions} sessions</div>
          </div>
          <table>
            <tr><th>Zone</th><th style="text-align:center">Sessions</th><th style="text-align:right">Revenue</th></tr>
            ${rows || '<tr><td colspan="3" style="text-align:center;color:#9ca3af">No data</td></tr>'}
          </table>
          <div class="footer">Laseria · laseriaapp@gmail.com</div>
        </body></html>`;

      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Revenue ${monthLabel}` });
    } catch (err) {
      Alert.alert(t('error'), err.message || t('exportFailed'));
    } finally {
      setExporting(false);
    }
  };

  // --- Export Excel (CSV — opens natively in Excel/Sheets) ---
  const exportExcel = async () => {
    if (!data) return;
    setExporting(true);
    try {
      const rows = [
        [`Revenue Report — ${monthLabel}`],
        [],
        ['Total Revenue', formatMoney(data.totalRevenue)],
        ['Total Appointments', data.appointmentCount],
        ['Total Sessions', data.totalSessions],
        [],
        ['Zone', 'Sessions', 'Revenue'],
        ...(data.byZone || []).map(z => [z.zone, z.sessions, formatMoney(z.revenue)]),
      ];

      const csv = rows.map(row => row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
      await Share.share({
        message: csv,
        title: `Revenue ${monthLabel}`,
      });
    } catch (err) {
      Alert.alert(t('error'), err.message || t('exportFailed'));
    } finally {
      setExporting(false);
    }
  };

  return (
    <LinearGradient colors={theme.gradientBackground} style={styles.container} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}>
      <StatusBar barStyle={isDark ? 'light-content' : 'dark-content'} translucent backgroundColor="transparent" />

      <View style={[styles.orb, styles.orbTop, { backgroundColor: theme.orbAccent }]} />
      <View style={[styles.orb, styles.orbBottom, { backgroundColor: theme.orbPrimary }]} />

      {/* Header */}
      <LinearGradient
        colors={theme.gradientHeader}
        style={[styles.header, { borderBottomColor: theme.headerBorder }]}
        start={{ x: 0, y: 0 }}
        end={{ x: 0, y: 1 }}
      >
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={24} color={theme.textPrimary} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: theme.textPrimary }]}>{t('revenue')}</Text>
        <View style={{ width: 32 }} />
      </LinearGradient>

      {/* Month navigator */}
      <View style={[styles.monthNav, { backgroundColor: theme.glassCard, borderColor: theme.glassCardBorder }]}>
        <TouchableOpacity onPress={prevMonth} style={styles.monthNavBtn}>
          <Ionicons name="chevron-back" size={22} color={theme.primary} />
        </TouchableOpacity>
        <Text style={[styles.monthLabel, { color: theme.textPrimary }]}>{monthLabel}</Text>
        <TouchableOpacity onPress={nextMonth} style={[styles.monthNavBtn, isCurrentMonth && { opacity: 0.3 }]} disabled={isCurrentMonth}>
          <Ionicons name="chevron-forward" size={22} color={theme.primary} />
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.centered}>
          <ActivityIndicator size="large" color={theme.primary} />
          <Text style={[styles.loadingText, { color: theme.textSecondary }]}>{t('loading')}</Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>

          {/* Total Revenue Card */}
          <LinearGradient colors={theme.gradientPrimary} style={styles.totalCard} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}>
            <Text style={[styles.totalLabel, { color: isDark ? 'rgba(0,0,0,0.6)' : 'rgba(255,255,255,0.8)' }]}>
              {t('totalRevenue')} · {selectedZone || t('allZones')}
            </Text>
            <Text style={[styles.totalAmount, { color: isDark ? '#111' : '#fff' }]}>
              {formatMoney(data?.totalRevenue)}
            </Text>
            <View style={styles.totalMeta}>
              <View style={styles.totalMetaItem}>
                <Ionicons name="calendar-outline" size={14} color={isDark ? 'rgba(0,0,0,0.5)' : 'rgba(255,255,255,0.75)'} />
                <Text style={[styles.totalMetaText, { color: isDark ? 'rgba(0,0,0,0.6)' : 'rgba(255,255,255,0.85)' }]}>
                  {data?.appointmentCount} {t('appointments').toLowerCase()}
                </Text>
              </View>
              <View style={styles.totalMetaItem}>
                <Ionicons name="flash-outline" size={14} color={isDark ? 'rgba(0,0,0,0.5)' : 'rgba(255,255,255,0.75)'} />
                <Text style={[styles.totalMetaText, { color: isDark ? 'rgba(0,0,0,0.6)' : 'rgba(255,255,255,0.85)' }]}>
                  {data?.totalSessions} {t('sessions').toLowerCase()}
                </Text>
              </View>
            </View>
          </LinearGradient>

          {/* Zone Filter */}
          {data?.byZone?.length > 0 && (
            <View style={styles.filterSection}>
              <Text style={[styles.sectionTitle, { color: theme.textSecondary }]}>{t('filterByZone')}</Text>
              <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterChips}>
                <TouchableOpacity
                  style={[styles.chip, { borderColor: theme.primary, backgroundColor: !selectedZone ? theme.primary + '20' : 'transparent' }]}
                  onPress={() => setSelectedZone(null)}
                >
                  <Text style={[styles.chipText, { color: theme.primary }]}>{t('allZones')}</Text>
                </TouchableOpacity>
                {data.byZone.map(z => (
                  <TouchableOpacity
                    key={z.zone}
                    style={[styles.chip, { borderColor: theme.primary, backgroundColor: selectedZone === z.zone ? theme.primary + '20' : 'transparent' }]}
                    onPress={() => setSelectedZone(z.zone)}
                  >
                    <Text style={[styles.chipText, { color: theme.primary }]}>{z.zone}</Text>
                  </TouchableOpacity>
                ))}
              </ScrollView>
            </View>
          )}

          {/* Zone Breakdown */}
          {data?.byZone?.length > 0 ? (
            <View style={[styles.breakdownCard, { backgroundColor: theme.glassCard, borderColor: theme.glassCardBorder }]}>
              <Text style={[styles.sectionTitle, { color: theme.textPrimary, marginBottom: 12 }]}>
                {t('revenueByZone')}
              </Text>
              {data.byZone.map((z, i) => {
                const pct = data.totalRevenue > 0 ? (z.revenue / data.totalRevenue) * 100 : 0;
                return (
                  <View key={z.zone} style={[styles.zoneRow, i < data.byZone.length - 1 && { borderBottomWidth: 1, borderBottomColor: theme.border }]}>
                    <View style={styles.zoneRowLeft}>
                      <Text style={[styles.zoneName, { color: theme.textPrimary }]}>{z.zone}</Text>
                      <Text style={[styles.zoneSessions, { color: theme.textTertiary }]}>
                        {z.sessions} {t('sessions').toLowerCase()}
                      </Text>
                      <View style={[styles.progressBar, { backgroundColor: theme.border }]}>
                        <View style={[styles.progressFill, { width: `${pct}%`, backgroundColor: theme.primary }]} />
                      </View>
                    </View>
                    <Text style={[styles.zoneRevenue, { color: theme.textPrimary }]}>
                      {formatMoney(z.revenue)}
                    </Text>
                  </View>
                );
              })}
            </View>
          ) : (
            <View style={[styles.emptyCard, { backgroundColor: theme.glassCard, borderColor: theme.glassCardBorder }]}>
              <Ionicons name="bar-chart-outline" size={48} color={theme.textTertiary} />
              <Text style={[styles.emptyText, { color: theme.textSecondary }]}>{t('noRevenueData')}</Text>
            </View>
          )}

          {/* Export Buttons */}
          <Text style={[styles.sectionTitle, { color: theme.textSecondary, marginBottom: 12 }]}>{t('exportRevenue')}</Text>
          <View style={styles.exportRow}>
            <TouchableOpacity
              style={[styles.exportBtn, { backgroundColor: theme.glassCard, borderColor: theme.glassCardBorder }, exporting && { opacity: 0.6 }]}
              onPress={exportPDF}
              disabled={exporting}
              activeOpacity={0.8}
            >
              {exporting
                ? <ActivityIndicator size="small" color="#EF4444" />
                : <Ionicons name="document-text-outline" size={22} color="#EF4444" />
              }
              <Text style={[styles.exportBtnText, { color: theme.textPrimary }]}>{t('exportPDF')}</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[styles.exportBtn, { backgroundColor: theme.glassCard, borderColor: theme.glassCardBorder }, exporting && { opacity: 0.6 }]}
              onPress={exportExcel}
              disabled={exporting}
              activeOpacity={0.8}
            >
              {exporting
                ? <ActivityIndicator size="small" color="#10B981" />
                : <Ionicons name="grid-outline" size={22} color="#10B981" />
              }
              <Text style={[styles.exportBtnText, { color: theme.textPrimary }]}>{t('exportExcel')}</Text>
            </TouchableOpacity>
          </View>

        </ScrollView>
      )}
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  orb: { position: 'absolute', borderRadius: 999 },
  orbTop: { width: 300, height: 300, top: -80, right: -100 },
  orbBottom: { width: 240, height: 240, bottom: 40, left: -90 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'ios' ? 56 : 36,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
  },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: 18, fontWeight: '800', letterSpacing: -0.4 },
  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 4,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  monthNavBtn: { padding: 10 },
  monthLabel: { fontSize: 17, fontWeight: '800', letterSpacing: -0.4 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12 },
  loadingText: { fontSize: 15, fontWeight: '600' },
  scrollContent: { padding: 20, paddingTop: 12, paddingBottom: 40 },
  totalCard: {
    borderRadius: 22,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  totalLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  totalAmount: {
    fontSize: 48,
    fontWeight: '800',
    letterSpacing: -2,
    marginBottom: 14,
  },
  totalMeta: { flexDirection: 'row', gap: 20 },
  totalMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  totalMetaText: { fontSize: 13, fontWeight: '600' },
  filterSection: { marginBottom: 16 },
  filterChips: { gap: 8, paddingRight: 4 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  chipText: { fontSize: 13, fontWeight: '700' },
  sectionTitle: { fontSize: 13, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 },
  breakdownCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 18,
    marginBottom: 24,
  },
  zoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    gap: 12,
  },
  zoneRowLeft: { flex: 1 },
  zoneName: { fontSize: 15, fontWeight: '700', marginBottom: 2 },
  zoneSessions: { fontSize: 12, fontWeight: '500', marginBottom: 6 },
  progressBar: {
    height: 4,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 2 },
  zoneRevenue: { fontSize: 17, fontWeight: '800', letterSpacing: -0.5 },
  emptyCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 40,
    alignItems: 'center',
    gap: 12,
    marginBottom: 24,
  },
  emptyText: { fontSize: 15, fontWeight: '500', textAlign: 'center' },
  exportRow: { flexDirection: 'row', gap: 12 },
  exportBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
  },
  exportBtnText: { fontSize: 14, fontWeight: '700' },
});
